### ISSUE TITLE
Code review of SemiConstantHeadersWriter.ts

### ISSUE THREAD

**Issue by joachimvh** [smessie/semi-constant-headers-writer-component#1]
Issue as this isn't part of a PR.

Instead of checking if `storageRoot` is defined in every loop iteration, you can just check when you first get the value and already return at that point if it's not defined, instead of going into the loop.

The 2 `return Promise.resolve(undefined)` lines can be removed.

https://github.com/smessie/semi-constant-headers-writer-component/blob/7987e62f92598e64e74e4ef3600884f154f9b34a/src/SemiConstantHeadersWriter.ts#L30-L36

Would replace the above block with `value = value.replace('{storageRoot}', storageRoot.path);`. This way you can combine headers both with and without the `{storageRoot}` in them in this class. If you really don't want this class to do anything else besides support headers with `{storageRoot}`, I would already check the values in the constructor an throw an error there, to prevent someone from accidentally misconfiguring and not knowing why their headers aren't being added. But I prefer the first solution.

So with all of the above and some simplification, I would write the handle function as follows:
```ts
public async handle(input: MetadataWriterInput): Promise<void> {
  const storageRoot = await this.storageStrategy.getStorageIdentifier(identifier);
  if (!storageRoot){
    this.logger.error(`Unable to find storage root: ${createErrorMessage(error)}`);
    return;
  }
  for (let [key, value] of this.headers) {
    addHeader(input.response, key, value.replace('{storageRoot}', storageRoot.path));
  }
}
```

**Comment by smessie** [comment]
The idea was that in the future other placeholders could be added.
By first checking (in the for-loop) if the value contains a `storageRoot` placeholder and then checking if such a storageRoot exists to replace the placeholder with, I skip that header if no such storageRoot exists because otherwise the placeholder couldn't be replaced properly.
For example, if I would add another `{webId}` placeholder, then I could have a header containing only that placeholder. However, in your suggestion, you would skip the header if the storageRoot is undefined even though the header might not even contain that placeholder.
In the same way, it would be nice to just support headers not containing any placeholders.
What I really want to do is skipping headers if they contain placeholders that cannot be replaced with a proper value.

I get the idea that I want to avoid checking if it is defined every loop iteration and it's a good suggestion, but I don't think it is possible given the above goals @joachimvh ?

**Comment by joachimvh** [comment]
My main opinion about that is that it's 5-10 lines of code, so if really necessary it can always be changed if necessary. It's all in one class so it doesn't have any architectural impact. If there ever are multiple placeholders then it would highly depend on what those are so it's hard to say anything about them already now. Take WebID as example. What if an account has multiple WebIDs? Which is planned for a future version. Then you might want to have a link header for each WebID which would require another loop for example.

It doesn't matter all that much though seeing as this is just a small class, there are just my opinons on how to make it more readable. Definitely remove the `Promise.resolve` lines though.

**Comment by smessie** [comment]
Thanks for the review. I've removed the `Promise.resolve` lines and added comments to improve the readability, but I prefer to leave the structure to allow easier addition of new placeholders in the future without having to restructure the whole class again, even for simple placeholders.
